package com.cienmilsabores.backendcienmil.model;

public enum Comuna {
    // Arica
    ARICA("Arica", Region.ARICA),
    CAMARONES("Camarones", Region.ARICA),
    PUTRE("Putre", Region.ARICA),
    GENERAL_LAGOS("General Lagos", Region.ARICA),

    // TARAPACA
    IQUIQUE("Iquique", Region.TARAPACA),
    ALTO_HOSPICIO("Alto Hospicio", Region.TARAPACA),
    POZO_ALMONTE("Pozo Almonte", Region.TARAPACA),
    CAMINNA("Camiña", Region.TARAPACA),
    COLCHANE("Colchane", Region.TARAPACA),
    HUARA("Huara", Region.TARAPACA),
    PICA("Pica", Region.TARAPACA),

    // ANTOFAGASTA
    ANTOFAGASTA("Antofagasta", Region.ANTOFAGASTA),
    MEJILLONES("Mejillones", Region.ANTOFAGASTA),
    SIERRA_GORDA("Sierra Gorda", Region.ANTOFAGASTA),
    TALTAL("Taltal", Region.ANTOFAGASTA),
    CALAMA("Calama", Region.ANTOFAGASTA),
    OLLAGUE("Ollagüe", Region.ANTOFAGASTA),
    SAN_PEDRO_DE_ATACAMA("San Pedro de Atacama", Region.ANTOFAGASTA),
    TOCOPILLA("Tocopilla", Region.ANTOFAGASTA),
    MARIA_ELENA("María Elena", Region.ANTOFAGASTA),
    
    // ATACAMA
    COPIAPO("Copiapó", Region.ATACAMA),
    CALDERA("Caldera", Region.ATACAMA),
    TIERRA_AMARILLA("Tierra Amarilla", Region.ATACAMA),
    CHAÑARAL("Chañaral", Region.ATACAMA),
    DIEGO_DE_ALMAGRO("Diego de Almagro", Region.ATACAMA),
    VALLENAR("Vallenar", Region.ATACAMA),
    ALTO_DEL_CARMEN("Alto del Carmen", Region.ATACAMA),
    FREIRINA("Freirina", Region.ATACAMA),
    HUASCO("Huasco", Region.ATACAMA),

    // COQUIMBO
    LA_SERENA("La Serena", Region.COQUIMBO),
    COQUIMBO("Coquimbo", Region.COQUIMBO),
    ANDACOLLO("Andacollo", Region.COQUIMBO),
    LA_HIGUERA("La Higuera", Region.COQUIMBO),
    PAIGUANO("Paihuano", Region.COQUIMBO),
    VICHUQUEN("Vicuña", Region.COQUIMBO),
    ILLAPEL("Illapel", Region.COQUIMBO),
    CANELA("Canela", Region.COQUIMBO),
    LOS_VILOS("Los Vilos", Region.COQUIMBO),
    SALAMANCA("Salamanca", Region.COQUIMBO),
    OVALLA("Ovalle", Region.COQUIMBO),
    COMBARBALA("Combarbalá", Region.COQUIMBO),
    MONTE_PATRIA("Monte Patria", Region.COQUIMBO),
    PUNITAQUI("Punitaqui", Region.COQUIMBO),
    RIO_HURTADO("Río Hurtado", Region.COQUIMBO),
    
    // Valparaíso
    VINA_DEL_MAR("Viña del Mar", Region.VALPARAISO),
    VALPARAISO("Valparaíso", Region.VALPARAISO),
    QUILPUE("Quilpué", Region.VALPARAISO),
    VILLA_ALEMANA("Villa Alemana", Region.VALPARAISO),
    CONCON("Concón", Region.VALPARAISO),
    CASABLANCA("Casablanca", Region.VALPARAISO),
    SAN_ANTONIO("San Antonio", Region.VALPARAISO),
    CARTAGENA("Cartagena", Region.VALPARAISO),
    EL_TABO("El Tabo", Region.VALPARAISO),
    EL_QUISCO("El Quisco", Region.VALPARAISO),
    LA_LIGUA("La Ligua", Region.VALPARAISO),
    CABO_DE_HORNOS("Cabo de Hornos", Region.MAGALLANES),
    JUAN_FERNANDEZ("Juan Fernández", Region.VALPARAISO),
    PUCHUN("Puchuncaví", Region.VALPARAISO),
    ZAPALLAR("Zapallar", Region.VALPARAISO),
    QUINTERO("Quintero", Region.VALPARAISO),
    LIMACHE("Limache", Region.VALPARAISO),
    OLMUE("Olmué", Region.VALPARAISO),
    SAN_FELIPE("San Felipe", Region.VALPARAISO),
    LOS_ANDES("Los Andes", Region.VALPARAISO),
    SAN_ESTEBAN("San Esteban", Region.VALPARAISO),
    SANTA_MARIA("Santa María", Region.VALPARAISO),
    PUTAENDO("Putaendo", Region.VALPARAISO),
    PANQUEHUE("Panquehue", Region.VALPARAISO),
    CALLE_LARGA("Calle Larga", Region.VALPARAISO),
    RINCONADA("Rinconada", Region.VALPARAISO),
    LLAYLLA("Llay-Llay", Region.VALPARAISO),
    CATEMU("Catemu", Region.VALPARAISO),
    SANTO_DOMINGO("Santo Domingo", Region.VALPARAISO),
    ALGARROBO("Algarrobo", Region.VALPARAISO),
    NOGALES("Nogales", Region.VALPARAISO),
    LA_CRUZ("La Cruz", Region.VALPARAISO),
    HIJUELAS("Hijuelas", Region.VALPARAISO),
    LA_CALERA("La Calera", Region.VALPARAISO),
    QUILLOTA("Quillota", Region.VALPARAISO),
    PETORCA("Petorca", Region.VALPARAISO),
    PAPUDO("Papudo", Region.VALPARAISO),
    CABILDO("Cabildo", Region.VALPARAISO),
    ISLA_DE_PASCUA("Isla de Pascua", Region.VALPARAISO),
    PUCHUNCAVI("Puchuncaví", Region.VALPARAISO),

    // LIBERTADOR GENERAL BERNARDO O'HIGGINS
    RANCAGUA("Rancagua", Region.OHIGGINS),
    MACHALI("Machalí", Region.OHIGGINS),
    GRANEROS("Graneros", Region.OHIGGINS),
    SAN_FERNANDO("San Fernando", Region.OHIGGINS),
    SANTA_CRUZ("Santa Cruz", Region.OHIGGINS),
    SAN_VICENTE("San Vicente", Region.OHIGGINS),
    PICHILEMU("Pichilemu", Region.OHIGGINS),
    COLTAUCO("Coltauco", Region.OHIGGINS),
    LA_ESTRELLA("La Estrella", Region.OHIGGINS),
    MARCHIGUE("Marchigüe", Region.OHIGGINS),
    NANCAGUA("Nancagua", Region.OHIGGINS),
    PALMILLA("Palmilla", Region.OHIGGINS),
    PERALILLO("Peralillo", Region.OHIGGINS),
    PUMANQUE("Pumanque", Region.OHIGGINS),
    CHIMBARONGO("Chimbarongo", Region.OHIGGINS),
    LAS_CABRAS("Las Cabras", Region.OHIGGINS),
    OLIVAR("Olivar", Region.OHIGGINS),
    PEUMO("Peumo", Region.OHIGGINS),
    SAN_FRANCISCO_DE_MOSTAZAL("San Francisco de Mostazal", Region.OHIGGINS),
    TALA("Tala", Region.OHIGGINS),
    DOÑIHUE("Doñihue", Region.OHIGGINS),
    COINCO("Coinco", Region.OHIGGINS),

    // MAULE
    TALCA("Talca", Region.MAULE),
    CURICO("Curicó", Region.MAULE),
    LINARES("Linares", Region.MAULE),
    CAUQUENES("Cauquenes", Region.MAULE),
    PARRAL("Parral", Region.MAULE),
    SAN_JAVIER("San Javier", Region.MAULE),
    VICHUQUEN2("Vichuquén", Region.MAULE),
    ROMERAL("Romeral", Region.MAULE),
    SAN_CLEMENTE("San Clemente", Region.MAULE),
    MAULE2("Maule", Region.MAULE),
    CURICO2("Curicó", Region.MAULE),
    HUALAÑE("Hualañé", Region.MAULE),
    RIO_CLARO("Río Claro", Region.MAULE),
    COLBUN("Colbún", Region.MAULE),
    LONGAVI("Longaví", Region.MAULE),
    RETIRO("Retiro", Region.MAULE),
    SAN_RAFAEL("San Rafael", Region.MAULE),
    LINARES2("Linares", Region.MAULE),
    YERBAS_BUENAS("Yerbabuena", Region.MAULE),
    VILLA_ALEGRE("Villa Alegre", Region.MAULE),

    // NUBLE
    CHILLAN("Chillán", Region.NUBLE),
    SAN_CARLOS("San Carlos", Region.NUBLE),
    BULNES("Bulnes", Region.NUBLE),
    YUNGAY("Yungay", Region.NUBLE),
    COIHUECO("Coihueco", Region.NUBLE),
    EL_CARMEN("El Carmen", Region.NUBLE),
    PEMUCO("Pemuco", Region.NUBLE),
    QUIRIHUE("Quirihue", Region.NUBLE),
    RANQUIL("Ránquil", Region.NUBLE),
    TREHUACO("Trehuaco", Region.NUBLE),
    SAN_IBAN("San Iban", Region.NUBLE),
    NINHUE("Ninhue", Region.NUBLE),
    PORTEZUELO("Portezuelo", Region.NUBLE),
    COELEMU("Coelemu", Region.NUBLE),
    RIO_CLARO2("Río Claro", Region.NUBLE),
    SAN_NICOLAS("San Nicolás", Region.NUBLE),
    TUCAPEL("Tucapel", Region.NUBLE),
    YUMBEL("Yumbel", Region.NUBLE),

    
    // Biobío
    CONCEPCION("Concepción", Region.BIOBIO),
    TALCAHUANO("Talcahuano", Region.BIOBIO),
    CHIGUAYANTE("Chiguayante", Region.BIOBIO),
    SAN_PEDRO("San Pedro de la Paz", Region.BIOBIO),
    HUALQUI("Hualqui", Region.BIOBIO),
    CORONEL("Coronel", Region.BIOBIO),
    LOTA("Lota", Region.BIOBIO),
    LOS_ANGELES("Los Ángeles", Region.BIOBIO),
    SANTA_BARBARA("Santa Bárbara", Region.BIOBIO),
    YUMBEL2("Yumbel", Region.BIOBIO),
    NACIMIENTO("Nacimiento", Region.BIOBIO),
    
    // ARAUCANIA
    TEMUCO("Temuco", Region.ARAUCANIA),
    VILCUN("Vilcún", Region.ARAUCANIA),
    PADRE_LAS_CASAS("Padre Las Casas", Region.ARAUCANIA),
    CARAHUE("Carahue", Region.ARAUCANIA),
    NUEVA_IMPERIAL("Nueva Imperial", Region.ARAUCANIA),
    PUCON("Pucón", Region.ARAUCANIA),
    ANGOL("Angol", Region.ARAUCANIA),
    RENAICO("Renaico", Region.ARAUCANIA),
    COLLIPULLI("Collipulli", Region.ARAUCANIA),
    VICTORIA("Victoria", Region.ARAUCANIA),
    LONCOCHE("Loncoche", Region.ARAUCANIA),
    FREIRE("Freire", Region.ARAUCANIA),
    LAUTARO("Lautaro", Region.ARAUCANIA),
    MELIPEUCO("Melipeuco", Region.ARAUCANIA),
    GORBEA("Gorbea", Region.ARAUCANIA),
    CARAHUE2("Carahue", Region.ARAUCANIA),

    // LOS RIOS
    VALDIVIA("Valdivia", Region.LOS_RIOS),
    LA_UNION("La Unión", Region.LOS_RIOS),
    RIO_BUENO("Río Bueno", Region.LOS_RIOS),
    LAGO_RANCO("Lago Ranco", Region.LOS_RIOS),
    FUTRONO("Futrono", Region.LOS_RIOS),
    PANGUIPULLI("Panguipulli", Region.LOS_RIOS),
    CORRAL("Corral", Region.LOS_RIOS),
    MARIQUINA("Mariquina", Region.LOS_RIOS),
    LOS_LAGOS("Los Lagos", Region.LOS_RIOS),
    Paillaco("Paillaco", Region.LOS_RIOS),
    SAN_JOSE_DE_LA_MARIQUINA("San José de la Mariquina", Region.LOS_RIOS),

    // LOS LAGOS
    PUERTO_MONTT("Puerto Montt", Region.LOS_LAGOS),
    CASTRO("Castro", Region.LOS_LAGOS),
    ANCUD("Ancud", Region.LOS_LAGOS),
    QUILLOTA2("Quellón", Region.LOS_LAGOS),
    OSORNO("Osorno", Region.LOS_LAGOS),
    PUERTO_VARAS("Puerto Varas", Region.LOS_LAGOS),
    PUERTO_OCTAY("Puerto Octay", Region.LOS_LAGOS),
    CALBUCO("Calbuco", Region.LOS_LAGOS),
    LLANQUIHUE("Llanquihue", Region.LOS_LAGOS),
    FRUTILLAR("Frutillar", Region.LOS_LAGOS),
    CHONCHI("Chonchi", Region.LOS_LAGOS),
    Dalcahue("Dalcahue", Region.LOS_LAGOS),
    QUEILEN("Quilén", Region.LOS_LAGOS),
    QUEMCHI("Quemchi", Region.LOS_LAGOS),
    QUELLON("Quellón", Region.LOS_LAGOS),

    // AYSEN
    COYHAIQUE("Coyhaique", Region.AYSEN),
    PUERTO_AYSEN("Puerto Aysén", Region.AYSEN),
    CISELLO("Cisnes", Region.AYSEN),
    GUAITECAS("Guaitecas", Region.AYSEN),
    LAGO_VERDE("Lago Verde", Region.AYSEN),
    OHIGGINS2("O'Higgins", Region.AYSEN),
    TORTEL("Tortel", Region.AYSEN),
    CHILE_CHICO("Chile Chico", Region.AYSEN),
    RIO_IBANEZ("Río Ibáñez", Region.AYSEN),
    MELINKA("Melinka", Region.AYSEN),
    
    // MAGALLANES Y LA ANTARTICA CHILENA
    PUNTA_ARENAS("Punta Arenas", Region.MAGALLANES),
    PORVENIR("Porvenir", Region.MAGALLANES),
    PRIMAVERA("Primavera", Region.MAGALLANES),
    LAGUNA_BLANCA("Laguna Blanca", Region.MAGALLANES),
    CAMPO_DE_HIELO_SUR("Campo de Hielo Sur", Region.MAGALLANES),
    RIO_VERDE("Río Verde", Region.MAGALLANES),
    SAN_GREGORIO("San Gregorio", Region.MAGALLANES),
    TORRES_DEL_PAINE("Torres del Paine", Region.MAGALLANES),
    ANTARTICA("Antártica", Region.MAGALLANES),

    // Región Metropolitana
    SANTIAGO("Santiago", Region.REGION_METROPOLITANA),
    PROVIDENCIA("Providencia", Region.REGION_METROPOLITANA),
    LAS_CONDES("Las Condes", Region.REGION_METROPOLITANA),
    NUÑOA("Ñuñoa", Region.REGION_METROPOLITANA),
    MAIPU("Maipú", Region.REGION_METROPOLITANA),
    LA_FLORIDA("La Florida", Region.REGION_METROPOLITANA),
    SAN_BERNARDO("San Bernardo", Region.REGION_METROPOLITANA),
    PUDAHUEL("Pudahuel", Region.REGION_METROPOLITANA),
    QUILICURA("Quilicura", Region.REGION_METROPOLITANA),
    CERRILLOS("Cerrillos", Region.REGION_METROPOLITANA),
    CURACAVI("Curacaví", Region.REGION_METROPOLITANA),
    LO_PRADO("Lo Prado", Region.REGION_METROPOLITANA),
    PENAFLOR("Peñaflor", Region.REGION_METROPOLITANA),
    COLINA("Colina", Region.REGION_METROPOLITANA),
    MELIPILLA("Melipilla", Region.REGION_METROPOLITANA),
    TALAGANTE("Talagante", Region.REGION_METROPOLITANA),
    PADRE_HURTADO("Padre Hurtado", Region.REGION_METROPOLITANA),
    ISLA_DE_MAIPO("Isla de Maipo", Region.REGION_METROPOLITANA),
    BUIN("Buin", Region.REGION_METROPOLITANA),
    CALERA_DE_TANGO("Calera de Tango", Region.REGION_METROPOLITANA),
    SAN_JOAQUIN("San Joaquín", Region.REGION_METROPOLITANA),
    LO_ESPEJO("Lo Espejo", Region.REGION_METROPOLITANA),
    EL_MONTE("El Monte", Region.REGION_METROPOLITANA),
    LA_CISTERNA("La Cisterna", Region.REGION_METROPOLITANA),
    SAN_PEDRO_DE_LA_PAZ("San Pedro de la Paz", Region.REGION_METROPOLITANA),
    MARIA_PINTO("María Pinto", Region.REGION_METROPOLITANA),
    ALHUEL("Alhué", Region.REGION_METROPOLITANA),
    PAINE("Paine", Region.REGION_METROPOLITANA),
    TIL_TIL("Tiltil", Region.REGION_METROPOLITANA),
    LAMPA("Lampa", Region.REGION_METROPOLITANA),
    SAN_JOSE_DE_MAIPO("San José de Maipo", Region.REGION_METROPOLITANA),
    PIRQUE("Pirque", Region.REGION_METROPOLITANA),
    PUENTE_ALTO("Puente Alto", Region.REGION_METROPOLITANA),
    VITACURA("Vitacura", Region.REGION_METROPOLITANA),
    SAN_RAMON("San Ramón", Region.REGION_METROPOLITANA),
    SAN_MIGUEL("San Miguel", Region.REGION_METROPOLITANA),
    RENCA("Renca", Region.REGION_METROPOLITANA),
    HUECHURABA("Huechuraba", Region.REGION_METROPOLITANA),
    RECOLETA("Recoleta", Region.REGION_METROPOLITANA),
    INDEPENDENCIA("Independencia", Region.REGION_METROPOLITANA),
    QUINTA_NORMAL("Quinta Normal", Region.REGION_METROPOLITANA),
    ESTACION_CENTRAL("Estación Central", Region.REGION_METROPOLITANA),
    PENNALOLEN("Peñalolén", Region.REGION_METROPOLITANA);
    
    
    private final String nombre;
    private final Region region;
    
    Comuna(String nombre, Region region) {
        this.nombre = nombre;
        this.region = region;
    }
    
    public String getNombre() {
        return nombre;
    }
    
    public Region getRegion() {
        return region;
    }

    @Override
    public String toString() {
        return this.name();
    }
}
